 const constants = {
  FETCH_ALL_NEWS:"FETCH_ALL_NEWS",
  ADD_NEWS:"ADD_NEWS",
  FETCH_ALL_BANNERS:"FETCH_ALL_BANNERS",
  ADD_FILTER_TMV3:"ADD_FILTER_TMV3",
  REMOVE_FILTER_TMV3:"REMOVE_FILTER_TMV3",
  APPLY_TMV3_FILTER:"APPLY_TMV3_FILTER",
  CLEAR_TMV3_FILTER:"CLEAR_TMV3_FILTER",
  FETCH_CIAS_ALL:"FETCH_CIAS_ALL",
  FETCH_CIAS_DETAIL:"FETCH_CIAS_DETAIL",
  FETCH_DTC_ALL:"FETCH_DTC_ALL",
  FETCH_DTC_DETAIL:"FETCH_DTC_DETAIL",
  FETCH_PDCERT_ALL:'FETCH_PDCERT_ALL',
  FETCH_PDCERT_DETAIL:"FETCH_PDCERT_DETAIL",
  ADD_ERROR:'ADD_ERROR',
  CLEAR_ERROR:'CLEAR_ERROR',
  ADD_SAVE_STATUS:"ADD_SAVE_STATUS"

};


export default constants;
